networks:
  marketplace-dev:
    driver: bridge
services:
  frontend-app:
    container_name: react-frontend
    build:
      context: ./marketplace-client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    depends_on:
      product_service_app:
        condition: service_started
      orchestrator_service_app:
        condition: service_started

  orchestrator_service_app:
    container_name: orchestrator_service
    build:
      context: ./OrchestratorService
      dockerfile: Dockerfile
    networks:
      - marketplace-dev
    ports:
      - "8084:8084"
    environment:
      JWTSECRET: my_important_secret
      BUY_SERVICE_ADDRESS_DEV: http://buy_service_app:8083
      ORDER_SERVICE_ADDRESS_DEV: http://order_service_app:8082
      USER_SERVICE_ADDRESS_DEV: http://user-service-app:8080
    depends_on:
      user-service-app:
        condition: service_started
      order_service_app:
        condition: service_started
      buy_service_app:
        condition: service_started

  postgres_buy_service_db:
    container_name: postgres_buy_service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace-buy-action-db
    ports:
      - "5435:5432"
    networks:
      - marketplace-dev
    volumes:
      - db_bs_data:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace-buy-action-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  buy_service_app:
    container_name: buy_service
    build:
      context: ./BuyService
      dockerfile: Dockerfile
    networks:
      - marketplace-dev
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres_buy_service_db
      DB_PORT: 5432
      DBUSER: postgres
      DBPASSWORD: password
      DBNAME: marketplace-buy-action-db
      JWTSECRET: my_important_secret
      ORDER_SERVICE_ADDRESS_DEV: http://order_service_app:8082
      PRODUCT_SERVICE_ADDRESS_DEV: http://product_service_app:8081
      USER_SERVICE_ADDRESS_DEV: http://user-service-app:8080
    depends_on:
      user-service-app:
        condition: service_started
      order_service_app:
        condition: service_started
      postgres_buy_service_db:
        condition: service_healthy   # wait for healthy Postgres

  postgres_order_service_db:
    container_name: postgres_order_service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace-shopping-cart-db
    ports:
      - "5434:5432"
    networks:
      - marketplace-dev
    volumes:
      - db_os_data:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace-shopping-cart-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  order_service_app:
    container_name: order_service
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    networks:
      - marketplace-dev
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres_order_service_db
      DB_PORT: 5432
      DBUSER: postgres
      DBPASSWORD: password
      DBNAME: marketplace-shopping-cart-db
      JWTSECRET: my_important_secret
      PRODUCT_SERVICE_ADDRESS_DEV: http://product_service_app:8081
      USER_SERVICE_ADDRESS_DEV: http://user-service-app:8080
    depends_on:
      product_service_app:
        condition: service_started
      user-service-app:
        condition: service_started
      postgres_order_service_db:
        condition: service_healthy   # wait for healthy Postgres

  postgres_product_service_db:
    container_name: postgres_product_service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace-product-catalog-db
    ports:
      - "5433:5432"
    networks:
      - marketplace-dev
    volumes:
      - db_ps_data:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace-product-catalog-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  product_service_app:
    container_name: product_service
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    networks:
      - marketplace-dev
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres_product_service_db
      DB_PORT: 5432
      DBUSER: postgres
      DBPASSWORD: password
      DBNAME: marketplace-product-catalog-db
      JWTSECRET: my_important_secret
    depends_on:
      postgres_product_service_db:
        condition: service_healthy   # wait for healthy Postgres

  postgres_user_service_db:
    container_name: postgres_user_service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace-users-db
    ports:
      - "5432:5432"
    networks:
      - marketplace-dev
    volumes:
      - db_us_data:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace-users-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  user-service-app:
    container_name: user-service
    build:
      context: ./UserService
      dockerfile: Dockerfile
    networks:
      - marketplace-dev
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres_user_service_db
      DB_PORT: 5432
      DBUSER: postgres
      DBPASSWORD: password
      DBNAME: marketplace-users-db
      JWTSECRET: my_important_secret
    depends_on:
      postgres_user_service_db:
        condition: service_healthy   # wait for healthy Postgres
volumes:
  db_us_data:
  db_ps_data:
  db_os_data:
  db_bs_data:
    