definitions:
  main.UpdateUserDto:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  main.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
      wallet:
        type: integer
    type: object
info:
  contact: {}
paths:
  /user-service/:
    patch:
      consumes:
      - application/json
      description: update user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UpdateUserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
    put:
      consumes:
      - application/json
      description: add user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
  /user-service/{id}:
    delete:
      consumes:
      - application/json
      description: delete user
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
    get:
      consumes:
      - application/json
      description: description of function that get user by id
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
  /user-service/get-all:
    get:
      consumes:
      - application/json
      description: description of function that get all users from DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetAll
      tags:
      - user-service
  /user-service/spend-money:
    post:
      consumes:
      - application/json
      description: spend money
      parameters:
      - description: Some ID
        in: query
        name: id
        type: string
      - description: Some money
        in: query
        name: money
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
  /user-service/test:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - user-service
  /user-service/wallet-replenishment:
    post:
      consumes:
      - application/json
      description: add money
      parameters:
      - description: Some ID
        in: query
        name: id
        type: string
      - description: Some money
        in: query
        name: money
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - user-service
swagger: "2.0"
