definitions:
  main.Product:
    properties:
      cost:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /product-service/:
    patch:
      consumes:
      - application/json
      description: update product
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - product-service
    put:
      consumes:
      - application/json
      description: add new product
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - product-service
  /product-service/{id}:
    delete:
      consumes:
      - application/json
      description: delete product
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - product-service
    get:
      consumes:
      - application/json
      description: description of function that get product by id
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - product-service
  /product-service/get-all:
    get:
      consumes:
      - application/json
      description: description of function that get all products from DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetAll
      tags:
      - product-service
swagger: "2.0"
